### ISSUE TITLE
可以Fork你的项目做二次开发吗？

### ISSUE THREAD

**Issue by coolicer** [giscafer/Ponitor#1]

**Comment by giscafer** [comment]
感兴趣可以一起做开发。
后期此项目会拓展统计功能，监听商品价格走势等；

当然项目License by MIT，可以随意免费使用，修改源码，最后给个说明出处即可了。

**Comment by coolicer** [comment]
@giscafer 我有一个域名挺适合，所以有空想做做。

**Comment by giscafer** [comment]
@coolicer OK的。
