### ISSUE TITLE
下架商品有问题

### ISSUE THREAD

**Issue by xugui0821** [giscafer/Ponitor#2]
只要关注的商品下架了就会每天发一封邮件来，价格随机
您关注的商品 【Youku优酷L2 无线路由器穿墙王5G双频WiFi智能家用宽带光纤】 涨价了，原价格：58，现价格：115

您关注的商品 【Youku优酷L2 无线路由器穿墙王5G双频WiFi智能家用宽带光纤】 涨价了，原价格：48，现价格：1199

您关注的商品 【Youku优酷L2 无线路由器穿墙王5G双频WiFi智能家用宽带光纤】 涨价了，原价格：129，现价格：149

**Comment by giscafer** [comment]
@xugui0821 提供一下商品链接，便于爬虫测试。

**Comment by giscafer** [comment]
已修改jd的爬虫方式。
