### ISSUE TITLE
要安装mongodb的吧？

### ISSUE THREAD

**Issue by paraofheaven** [giscafer/Ponitor#4]
要安装mongodb的吧？会报这样的错误：
![error](https://ss3.baidu.com/7LsWdDW5_xN3otqbppnN2DJv/pass/;q=90;g=0/sign=245958eb1fce36d3ee488b390ac85dba/9f2f070828381f3096c82998a3014c086e06f02a.jpg)

**Comment by giscafer** [comment]
是的，安装后启动mongodb服务就可以了
