### ISSUE TITLE
天猫|淘宝 专栏对于已下架商品的监控有问题！

### ISSUE THREAD

**Issue by jiey2016** [giscafer/Ponitor#6]
已下架商品会显示错误价格，并且会发邮件提醒。望修复！

**Comment by giscafer** [comment]
@jiey2016 给个发邮件了那个商品链接，好测试

**Comment by jiey2016** [comment]
@giscafer 
https://detail.tmall.com/item.htm?abtest=_AB-LR129-PR129&pvid=1351e451-efcf-4833-8a82-71cb1930f0ba&pos=1&abbucket=_AB-M129_B3&acm=03130.1003.1.701602&id=39954179527&scm=1007.12929.25829.100200300000000

https://detail.tmall.com/item.htm?abtest=_AB-LR129-PR129&pvid=12a38cf3-4f3a-436f-a4f8-112f18b04d69&pos=1&abbucket=_AB-M129_B3&acm=03130.1003.1.701602&id=536389117691&scm=1007.12929.25829.100200300000000

**Comment by giscafer** [comment]
fix bug https://github.com/giscafer/Ponitor/commit/9a00e96e3b55ccf900d1683fb48f728d538c5ab9
